spring:
    datasource:
        url: jdbc:mysql://rm-uf6r00howqec9yh2m8o.mysql.rds.aliyuncs.com:3306/test?serverTimezone=UTC
        username: edric
        password: TcGJnl1r594TuC2h7C
    thymeleaf:
        cache: false
        encoding: utf-8
    mvc:
        format:
            date: yyyy-MM-dd

mybatis:
    mapper-locations: classpath:mapper/*Mapper.xml  #mapper映射文件
    type-aliases-package: com.example.demo01.domain
#  config-location:  #指定核心配置文件
server:
    port: 8081


