spring:
    datasource:
        url: jdbc:mysql://localhost:3306/test?serverTimezone=UTC
        username: edric
        password: gjm2580
    thymeleaf:
        cache: false
        encoding: utf-8

server:
    port: 8081


